'use client'

import { Brain, TrendingUp, AlertCircle, XCircle, BookOpen, Zap, Lightbulb, CheckCircle } from 'lucide-react'
import { Card, CardContent, CardHeader } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import type { Sentiment, SentimentLabel } from '@/types'

interface Props { sentiment: Sentiment }

type SentimentVariant = 'positive' | 'mixed' | 'negative'

const CFG: Record<SentimentLabel, {
    variant: SentimentVariant
    icon: React.ReactNode
    barColor: string
    scoreColor: string
}> = {
    positive: {
        variant: 'positive',
        icon: <TrendingUp className="h-3 w-3" />,
        barColor: 'bg-emerald-500',
        scoreColor: 'text-emerald-400',
    },
    mixed: {
        variant: 'mixed',
        icon: <AlertCircle className="h-3 w-3" />,
        barColor: 'bg-amber-500',
        scoreColor: 'text-amber-400',
    },
    negative: {
        variant: 'negative',
        icon: <XCircle className="h-3 w-3" />,
        barColor: 'bg-red-500',
        scoreColor: 'text-red-400',
    },
}

export default function SentimentCard({ sentiment }: Props) {
    const cfg = CFG[sentiment.sentiment] ?? CFG.mixed

    return (
        <div className="mt-8 space-y-4 animate-fade-up">

            {/* ── Section header ─────────────────────────────────────────────────── */}
            <div className="flex items-center gap-3">
                <div className="h-9 w-9 rounded-xl shrink-0 flex items-center justify-center"
                    style={{ background: 'linear-gradient(135deg, var(--gold), var(--gold-light))' }}>
                    <Brain className="h-4.5 w-4.5 text-background" style={{ color: '#07070E' }} />
                </div>
                <div className="flex-1">
                    <h2 className="font-display text-xl text-foreground leading-tight">AI Summary</h2>
                    <p className="text-[10px] text-muted-foreground">
                        {sentiment.isFallback ? 'Derived from IMDb metadata' : 'Generated by OpenAI GPT-4o-mini'}
                        {sentiment.wordCount ? ` · ${sentiment.wordCount} words` : ''}
                    </p>
                </div>
                <Badge variant={cfg.variant}>
                    {cfg.icon}
                    {sentiment.sentiment.charAt(0).toUpperCase() + sentiment.sentiment.slice(1)}
                </Badge>
            </div>

            {/* ── Score bar ──────────────────────────────────────────────────────── */}
            <Card>
                <CardContent className="p-5">
                    <div className="flex justify-between items-baseline mb-3">
                        <p className="text-[10px] uppercase tracking-widest text-muted-foreground">Audience Score</p>
                        <p className={`font-display text-3xl font-semibold ${cfg.scoreColor}`}>
                            {sentiment.score}
                            <span className="text-sm font-body font-normal text-muted-foreground">/100</span>
                        </p>
                    </div>
                    <div className="h-2 w-full rounded-full bg-secondary overflow-hidden">
                        <div
                            className={`h-full rounded-full ${cfg.barColor} transition-all duration-1000`}
                            style={{ width: `${sentiment.score}%` }}
                        />
                    </div>
                </CardContent>
            </Card>

            {/* ── Editorial summary ──────────────────────────────────────────────── */}
            <Card className="animate-fade-up [animation-delay:60ms]">
                <CardHeader className="pb-3">
                    <h3 className="flex items-center gap-2 font-display text-base text-[var(--gold)]">
                        <BookOpen className="h-3.5 w-3.5" /> Editorial Analysis
                    </h3>
                </CardHeader>
                <CardContent className="pt-0">
                    <p className="text-sm leading-[1.95] text-muted-foreground tracking-wide whitespace-pre-wrap">
                        {sentiment.summary}
                    </p>
                </CardContent>
            </Card>

            {/* ── Highlights + Themes ────────────────────────────────────────────── */}
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">

                {/* Highlights */}
                <Card className="animate-fade-up [animation-delay:100ms]">
                    <CardHeader className="pb-3">
                        <h3 className="flex items-center gap-2 font-display text-base text-[var(--gold)]">
                            <Zap className="h-3.5 w-3.5" /> Highlights
                        </h3>
                    </CardHeader>
                    <CardContent className="pt-0 space-y-3">
                        {sentiment.highlights.map((h, i) => (
                            <div key={i} className="flex gap-3 items-start">
                                <span className="h-5 w-5 rounded-md shrink-0 mt-0.5 flex items-center justify-center text-[10px] font-bold text-[var(--gold)]"
                                    style={{ background: 'var(--gold-dim)' }}>
                                    {i + 1}
                                </span>
                                <p className="text-sm text-muted-foreground leading-relaxed">{h}</p>
                            </div>
                        ))}
                    </CardContent>
                </Card>

                {/* Key Themes */}
                <Card className="animate-fade-up [animation-delay:140ms]">
                    <CardHeader className="pb-3">
                        <h3 className="flex items-center gap-2 font-display text-base text-[var(--gold)]">
                            <Lightbulb className="h-3.5 w-3.5" /> Key Themes
                        </h3>
                    </CardHeader>
                    <CardContent className="pt-0 space-y-2.5">
                        {sentiment.themes.map((t, i) => (
                            <div key={i} className="rounded-lg bg-secondary border border-border px-3 py-2 text-sm text-foreground">
                                {t}
                            </div>
                        ))}
                    </CardContent>
                </Card>
            </div>

            {/* ── Recommendation ─────────────────────────────────────────────────── */}
            <Card className={`animate-fade-up [animation-delay:180ms] ${sentiment.recommended
                ? 'border-emerald-500/20 bg-emerald-500/5'
                : 'border-red-500/20 bg-red-500/5'
                }`}>
                <CardContent className="p-4 flex items-center gap-3">
                    {sentiment.recommended
                        ? <CheckCircle className="h-5 w-5 shrink-0 text-emerald-400" />
                        : <XCircle className="h-5 w-5 shrink-0 text-red-400" />
                    }
                    <div>
                        <p className={`font-semibold text-sm mb-0.5 ${sentiment.recommended ? 'text-emerald-400' : 'text-red-400'}`}>
                            {sentiment.recommended ? 'Recommended Watch' : 'Not Recommended'}
                        </p>
                        <p className="text-xs text-muted-foreground">
                            {sentiment.recommended
                                ? 'The AI analysis suggests this film is worth your time.'
                                : 'The AI analysis suggests approaching this film cautiously.'}
                        </p>
                    </div>
                </CardContent>
            </Card>
        </div>
    )
}